ALTER TABLE accounts ADD COLUMN IF NOT EXISTS runtime_status TEXT NOT NULL DEFAULT 'READY';
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS runtime_status_detail TEXT;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS runtime_status_at TIMESTAMPTZ;
