CREATE TABLE traffic_policies (
 id UUID PRIMARY KEY,
 account_id UUID NOT NULL UNIQUE REFERENCES accounts(id) ON DELETE CASCADE,
 min_samples INTEGER NOT NULL DEFAULT 5,
 alpha DOUBLE PRECISION NOT NULL DEFAULT 0.2,
 sigma_multiplier DOUBLE PRECISION NOT NULL DEFAULT 4,
 min_bps DOUBLE PRECISION NOT NULL DEFAULT 0,
 hard_bps DOUBLE PRECISION NOT NULL DEFAULT 0,
 confirmations INTEGER NOT NULL DEFAULT 3,
 action TEXT NOT NULL DEFAULT 'ALERT' CHECK(action IN ('LOG','ALERT','DISABLE_CLIENT')),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
