// Code generated from system ISO 3166 data; DO NOT EDIT.
package geoctx

var countryNameToCode = map[string]string{
	"afghanistan":                      "af",
	"albania":                          "al",
	"algeria":                          "dz",
	"american samoa":                   "as",
	"andorra":                          "ad",
	"angola":                           "ao",
	"anguilla":                         "ai",
	"antarctica":                       "aq",
	"antigua and barbuda":              "ag",
	"arab republic of egypt":           "eg",
	"argentina":                        "ar",
	"argentine republic":               "ar",
	"armenia":                          "am",
	"aruba":                            "aw",
	"australia":                        "au",
	"austria":                          "at",
	"azerbaijan":                       "az",
	"bahamas":                          "bs",
	"bahrain":                          "bh",
	"bangladesh":                       "bd",
	"barbados":                         "bb",
	"belarus":                          "by",
	"belgium":                          "be",
	"belize":                           "bz",
	"benin":                            "bj",
	"bermuda":                          "bm",
	"bhutan":                           "bt",
	"bolivarian republic of venezuela": "ve",
	"bolivia":                          "bo",
	"bolivia, plurinational state of":  "bo",
	"bonaire, sint eustatius and saba": "bq",
	"bosnia and herzegovina":           "ba",
	"botswana":                         "bw",
	"bouvet island":                    "bv",
	"brazil":                           "br",
	"britain":                          "gb",
	"british indian ocean territory":   "io",
	"british virgin islands":           "vg",
	"brunei darussalam":                "bn",
	"bulgaria":                         "bg",
	"burkina faso":                     "bf",
	"burundi":                          "bi",
	"cabo verde":                       "cv",
	"cambodia":                         "kh",
	"cameroon":                         "cm",
	"canada":                           "ca",
	"cayman islands":                   "ky",
	"central african republic":         "cf",
	"chad":                             "td",
	"chile":                            "cl",
	"china":                            "cn",
	"christmas island":                 "cx",
	"cocos (keeling) islands":          "cc",
	"colombia":                         "co",
	"commonwealth of dominica":         "dm",
	"commonwealth of the bahamas":      "bs",
	"commonwealth of the northern mariana islands": "mp",
	"comoros":                               "km",
	"congo":                                 "cg",
	"congo, the democratic republic of the": "cd",
	"cook islands":                          "ck",
	"costa rica":                            "cr",
	"croatia":                               "hr",
	"cuba":                                  "cu",
	"cura\u00e7ao":                          "cw",
	"cyprus":                                "cy",
	"czech republic":                        "cz",
	"czechia":                               "cz",
	"c\u00f4te d'ivoire":                    "ci",
	"democratic people's republic of korea": "kp",
	"democratic republic of sao tome and principe": "st",
	"democratic republic of timor-leste":           "tl",
	"democratic socialist republic of sri lanka":   "lk",
	"denmark":                     "dk",
	"djibouti":                    "dj",
	"dominica":                    "dm",
	"dominican republic":          "do",
	"eastern republic of uruguay": "uy",
	"ecuador":                     "ec",
	"egypt":                       "eg",
	"el salvador":                 "sv",
	"equatorial guinea":           "gq",
	"eritrea":                     "er",
	"estonia":                     "ee",
	"eswatini":                    "sz",
	"ethiopia":                    "et",
	"falkland islands (malvinas)": "fk",
	"faroe islands":               "fo",
	"federal democratic republic of ethiopia": "et",
	"federal democratic republic of nepal":    "np",
	"federal republic of germany":             "de",
	"federal republic of nigeria":             "ng",
	"federal republic of somalia":             "so",
	"federated states of micronesia":          "fm",
	"federative republic of brazil":           "br",
	"fiji":                                    "fj",
	"finland":                                 "fi",
	"france":                                  "fr",
	"french guiana":                           "gf",
	"french polynesia":                        "pf",
	"french republic":                         "fr",
	"french southern territories":             "tf",
	"gabon":                                   "ga",
	"gabonese republic":                       "ga",
	"gambia":                                  "gm",
	"georgia":                                 "ge",
	"germany":                                 "de",
	"ghana":                                   "gh",
	"gibraltar":                               "gi",
	"grand duchy of luxembourg":               "lu",
	"great britain":                           "gb",
	"greece":                                  "gr",
	"greenland":                               "gl",
	"grenada":                                 "gd",
	"guadeloupe":                              "gp",
	"guam":                                    "gu",
	"guatemala":                               "gt",
	"guernsey":                                "gg",
	"guinea":                                  "gn",
	"guinea-bissau":                           "gw",
	"guyana":                                  "gy",
	"haiti":                                   "ht",
	"hashemite kingdom of jordan":             "jo",
	"heard island and mcdonald islands":       "hm",
	"hellenic republic":                       "gr",
	"holy see (vatican city state)":           "va",
	"honduras":                                "hn",
	"hong kong":                               "hk",
	"hong kong special administrative region of china": "hk",
	"hungary":                                "hu",
	"iceland":                                "is",
	"independent state of papua new guinea":  "pg",
	"independent state of samoa":             "ws",
	"india":                                  "in",
	"indonesia":                              "id",
	"iran":                                   "ir",
	"iran, islamic republic of":              "ir",
	"iraq":                                   "iq",
	"ireland":                                "ie",
	"islamic republic of afghanistan":        "af",
	"islamic republic of iran":               "ir",
	"islamic republic of mauritania":         "mr",
	"islamic republic of pakistan":           "pk",
	"isle of man":                            "im",
	"israel":                                 "il",
	"italian republic":                       "it",
	"italy":                                  "it",
	"jamaica":                                "jm",
	"japan":                                  "jp",
	"jersey":                                 "je",
	"jordan":                                 "jo",
	"kazakhstan":                             "kz",
	"kenya":                                  "ke",
	"kingdom of bahrain":                     "bh",
	"kingdom of belgium":                     "be",
	"kingdom of bhutan":                      "bt",
	"kingdom of cambodia":                    "kh",
	"kingdom of denmark":                     "dk",
	"kingdom of eswatini":                    "sz",
	"kingdom of lesotho":                     "ls",
	"kingdom of morocco":                     "ma",
	"kingdom of norway":                      "no",
	"kingdom of saudi arabia":                "sa",
	"kingdom of spain":                       "es",
	"kingdom of sweden":                      "se",
	"kingdom of thailand":                    "th",
	"kingdom of the netherlands":             "nl",
	"kingdom of tonga":                       "to",
	"kiribati":                               "ki",
	"korea, democratic people's republic of": "kp",
	"korea, republic of":                     "kr",
	"kuwait":                                 "kw",
	"kyrgyz republic":                        "kg",
	"kyrgyzstan":                             "kg",
	"lao people's democratic republic":       "la",
	"laos":                                   "la",
	"latvia":                                 "lv",
	"lebanese republic":                      "lb",
	"lebanon":                                "lb",
	"lesotho":                                "ls",
	"liberia":                                "lr",
	"libya":                                  "ly",
	"liechtenstein":                          "li",
	"lithuania":                              "lt",
	"luxembourg":                             "lu",
	"macao":                                  "mo",
	"macao special administrative region of china": "mo",
	"madagascar":                      "mg",
	"malawi":                          "mw",
	"malaysia":                        "my",
	"maldives":                        "mv",
	"mali":                            "ml",
	"malta":                           "mt",
	"marshall islands":                "mh",
	"martinique":                      "mq",
	"mauritania":                      "mr",
	"mauritius":                       "mu",
	"mayotte":                         "yt",
	"mexico":                          "mx",
	"micronesia, federated states of": "fm",
	"moldova":                         "md",
	"moldova, republic of":            "md",
	"monaco":                          "mc",
	"mongolia":                        "mn",
	"montenegro":                      "me",
	"montserrat":                      "ms",
	"morocco":                         "ma",
	"mozambique":                      "mz",
	"myanmar":                         "mm",
	"namibia":                         "na",
	"nauru":                           "nr",
	"nepal":                           "np",
	"netherlands":                     "nl",
	"new caledonia":                   "nc",
	"new zealand":                     "nz",
	"nicaragua":                       "ni",
	"niger":                           "ne",
	"nigeria":                         "ng",
	"niue":                            "nu",
	"norfolk island":                  "nf",
	"north korea":                     "kp",
	"north macedonia":                 "mk",
	"northern mariana islands":        "mp",
	"norway":                          "no",
	"oman":                            "om",
	"pakistan":                        "pk",
	"palau":                           "pw",
	"palestine, state of":             "ps",
	"panama":                          "pa",
	"papua new guinea":                "pg",
	"paraguay":                        "py",
	"people's democratic republic of algeria":      "dz",
	"people's republic of bangladesh":              "bd",
	"people's republic of china":                   "cn",
	"peru":                                         "pe",
	"philippines":                                  "ph",
	"pitcairn":                                     "pn",
	"plurinational state of bolivia":               "bo",
	"poland":                                       "pl",
	"portugal":                                     "pt",
	"portuguese republic":                          "pt",
	"principality of andorra":                      "ad",
	"principality of liechtenstein":                "li",
	"principality of monaco":                       "mc",
	"puerto rico":                                  "pr",
	"qatar":                                        "qa",
	"republic of albania":                          "al",
	"republic of angola":                           "ao",
	"republic of armenia":                          "am",
	"republic of austria":                          "at",
	"republic of azerbaijan":                       "az",
	"republic of belarus":                          "by",
	"republic of benin":                            "bj",
	"republic of bosnia and herzegovina":           "ba",
	"republic of botswana":                         "bw",
	"republic of bulgaria":                         "bg",
	"republic of burundi":                          "bi",
	"republic of cabo verde":                       "cv",
	"republic of cameroon":                         "cm",
	"republic of chad":                             "td",
	"republic of chile":                            "cl",
	"republic of colombia":                         "co",
	"republic of costa rica":                       "cr",
	"republic of croatia":                          "hr",
	"republic of cuba":                             "cu",
	"republic of cyprus":                           "cy",
	"republic of c\u00f4te d'ivoire":               "ci",
	"republic of djibouti":                         "dj",
	"republic of ecuador":                          "ec",
	"republic of el salvador":                      "sv",
	"republic of equatorial guinea":                "gq",
	"republic of estonia":                          "ee",
	"republic of fiji":                             "fj",
	"republic of finland":                          "fi",
	"republic of ghana":                            "gh",
	"republic of guatemala":                        "gt",
	"republic of guinea":                           "gn",
	"republic of guinea-bissau":                    "gw",
	"republic of guyana":                           "gy",
	"republic of haiti":                            "ht",
	"republic of honduras":                         "hn",
	"republic of iceland":                          "is",
	"republic of india":                            "in",
	"republic of indonesia":                        "id",
	"republic of iraq":                             "iq",
	"republic of kazakhstan":                       "kz",
	"republic of kenya":                            "ke",
	"republic of kiribati":                         "ki",
	"republic of latvia":                           "lv",
	"republic of liberia":                          "lr",
	"republic of lithuania":                        "lt",
	"republic of madagascar":                       "mg",
	"republic of malawi":                           "mw",
	"republic of maldives":                         "mv",
	"republic of mali":                             "ml",
	"republic of malta":                            "mt",
	"republic of mauritius":                        "mu",
	"republic of moldova":                          "md",
	"republic of mozambique":                       "mz",
	"republic of myanmar":                          "mm",
	"republic of namibia":                          "na",
	"republic of nauru":                            "nr",
	"republic of nicaragua":                        "ni",
	"republic of north macedonia":                  "mk",
	"republic of palau":                            "pw",
	"republic of panama":                           "pa",
	"republic of paraguay":                         "py",
	"republic of peru":                             "pe",
	"republic of poland":                           "pl",
	"republic of san marino":                       "sm",
	"republic of senegal":                          "sn",
	"republic of serbia":                           "rs",
	"republic of seychelles":                       "sc",
	"republic of sierra leone":                     "sl",
	"republic of singapore":                        "sg",
	"republic of slovenia":                         "si",
	"republic of south africa":                     "za",
	"republic of south sudan":                      "ss",
	"republic of suriname":                         "sr",
	"republic of tajikistan":                       "tj",
	"republic of the congo":                        "cg",
	"republic of the gambia":                       "gm",
	"republic of the marshall islands":             "mh",
	"republic of the niger":                        "ne",
	"republic of the philippines":                  "ph",
	"republic of the sudan":                        "sd",
	"republic of trinidad and tobago":              "tt",
	"republic of tunisia":                          "tn",
	"republic of t\u00fcrkiye":                     "tr",
	"republic of uganda":                           "ug",
	"republic of uzbekistan":                       "uz",
	"republic of vanuatu":                          "vu",
	"republic of yemen":                            "ye",
	"republic of zambia":                           "zm",
	"republic of zimbabwe":                         "zw",
	"romania":                                      "ro",
	"russia":                                       "ru",
	"russian federation":                           "ru",
	"rwanda":                                       "rw",
	"rwandese republic":                            "rw",
	"r\u00e9union":                                 "re",
	"saint barth\u00e9lemy":                        "bl",
	"saint helena, ascension and tristan da cunha": "sh",
	"saint kitts and nevis":                        "kn",
	"saint lucia":                                  "lc",
	"saint martin (french part)":                   "mf",
	"saint pierre and miquelon":                    "pm",
	"saint vincent and the grenadines":             "vc",
	"samoa":                                        "ws",
	"san marino":                                   "sm",
	"sao tome and principe":                        "st",
	"saudi arabia":                                 "sa",
	"senegal":                                      "sn",
	"serbia":                                       "rs",
	"seychelles":                                   "sc",
	"sierra leone":                                 "sl",
	"singapore":                                    "sg",
	"sint maarten (dutch part)":                    "sx",
	"slovak republic":                              "sk",
	"slovakia":                                     "sk",
	"slovenia":                                     "si",
	"socialist republic of viet nam":               "vn",
	"solomon islands":                              "sb",
	"somalia":                                      "so",
	"south africa":                                 "za",
	"south georgia and the south sandwich islands": "gs",
	"south korea":                                  "kr",
	"south sudan":                                  "ss",
	"spain":                                        "es",
	"sri lanka":                                    "lk",
	"state of israel":                              "il",
	"state of kuwait":                              "kw",
	"state of qatar":                               "qa",
	"sudan":                                        "sd",
	"sultanate of oman":                            "om",
	"suriname":                                     "sr",
	"svalbard and jan mayen":                       "sj",
	"sweden":                                       "se",
	"swiss confederation":                          "ch",
	"switzerland":                                  "ch",
	"syria":                                        "sy",
	"syrian arab republic":                         "sy",
	"taiwan":                                       "tw",
	"taiwan, province of china":                    "tw",
	"tajikistan":                                   "tj",
	"tanzania":                                     "tz",
	"tanzania, united republic of":                 "tz",
	"thailand":                                     "th",
	"the state of eritrea":                         "er",
	"the state of palestine":                       "ps",
	"timor-leste":                                  "tl",
	"togo":                                         "tg",
	"togolese republic":                            "tg",
	"tokelau":                                      "tk",
	"tonga":                                        "to",
	"trinidad and tobago":                          "tt",
	"tunisia":                                      "tn",
	"turkmenistan":                                 "tm",
	"turks and caicos islands":                     "tc",
	"tuvalu":                                       "tv",
	"t\u00fcrkiye":                                 "tr",
	"u.s.a.":                                       "us",
	"uganda":                                       "ug",
	"uk":                                           "gb",
	"ukraine":                                      "ua",
	"union of the comoros":                         "km",
	"united arab emirates":                         "ae",
	"united kingdom":                               "gb",
	"united kingdom of great britain and northern ireland": "gb",
	"united mexican states":                                "mx",
	"united republic of tanzania":                          "tz",
	"united states":                                        "us",
	"united states minor outlying islands":                 "um",
	"united states of america":                             "us",
	"uruguay":                                              "uy",
	"usa":                                                  "us",
	"uzbekistan":                                           "uz",
	"vanuatu":                                              "vu",
	"venezuela":                                            "ve",
	"venezuela, bolivarian republic of":                    "ve",
	"viet nam":                                             "vn",
	"vietnam":                                              "vn",
	"virgin islands of the united states":                  "vi",
	"virgin islands, british":                              "vg",
	"virgin islands, u.s.":                                 "vi",
	"wallis and futuna":                                    "wf",
	"western sahara":                                       "eh",
	"yemen":                                                "ye",
	"zambia":                                               "zm",
	"zimbabwe":                                             "zw",
	"\u00e5land islands":                                   "ax",
}
