#!/usr/bin/env python3
import json,os,hashlib,random,subprocess
ROOT=os.path.abspath(os.path.join(os.path.dirname(__file__),'..'));os.chdir(ROOT);X=json.load(open('docs/SOURCE_INTERNALIZATION_BRAIN.json'));T=json.load(open('docs/SYMBOL_TOPOLOGY_MEMORY_PACK.json'));seed=int(X['source_commit'][:12],16);rng=random.Random(seed)
# 30 conceptual symbols with useful evidence, 30 topology prompts, 20 verbatim blocks.
concept=[x for x in X['symbol_memory'] if x['calls'] or x['db_reads'] or x['db_writes'] or x['routes'] or x['side_effects']]; concept=rng.sample(concept,min(30,len(concept)))
files=[x for x in T['files'] if len(x['symbols'])>=2]; topo=rng.sample(files,min(20,len(files))); routes=rng.sample(T['routes'],min(10,len(T['routes']))); blocks=rng.sample([x for x in X['source_blocks'] if x['end_line']-x['start_line']+1>=5],20)
qs=[];keys={}
def add(kind,prompt,key):
 i=len(qs)+1;qs.append({'id':i,'metric':kind,'prompt':prompt});keys[str(i)]=key
for x in concept:add('conceptual',f"Without lookup: describe the implementation topology of symbol `{x['symbol']}` in `{x['file']}`: package, signature, immediate previous/next symbol, calls, DB reads/writes, routes and side effects.",{'package':x['package'],'signature':x['signature'],'previous_symbol':x['previous_symbol'],'next_symbol':x['next_symbol'],'calls':x['calls'],'db_reads':x['db_reads'],'db_writes':x['db_writes'],'routes':x['routes'],'side_effects':x['side_effects']})
for x in topo:add('topology',f"Without lookup: list the ordered symbols in `{x['file']}`.",{'symbols':x['symbols']})
for x in routes:add('topology',f"Without lookup: give the handler name for `{x['method']} {x['path']}`.",{'handler':x['handler']})
for x in blocks:add('verbatim',f"Without lookup: reproduce exactly lines {x['start_line']}-{x['end_line']} of `{x['file']}` including indentation and punctuation.",{'text':x['text']})
os.makedirs('.audit/unaided-memory-baseline',exist_ok=True);kp='.audit/unaided-memory-baseline/key.json';json.dump({'source_commit':X['source_commit'],'keys':keys},open(kp,'w'),ensure_ascii=False,indent=2);open(kp,'a').write('\n');kh=hashlib.sha256(open(kp,'rb').read()).hexdigest();pub={'schema_version':1,'source_commit':X['source_commit'],'question_count':len(qs),'rules':['No repository, Brain, server, tools, files, prior answer keys, search, or lookup may be consulted while answering.','Answer from active conversational/model recall only.','Freeze answers before grading.'], 'questions':qs};json.dump(pub,open('docs/UNAIDED_SOURCE_MEMORY_BASELINE_EXAM.json','w'),ensure_ascii=False,indent=2);open('docs/UNAIDED_SOURCE_MEMORY_BASELINE_EXAM.json','a').write('\n');open('docs/UNAIDED_SOURCE_MEMORY_BASELINE_EXAM.md','w').write(f'# Unaided Source Memory Baseline Exam\n\n**{len(qs)} blind questions**: 30 conceptual, 30 topology/name, 20 verbatim. No lookup is permitted during answering. Private key SHA256: `{kh}`.\n\nThis exam measures model/chat recall, not retrieval capability.\n');print('baseline',len(qs),'key',kh)
